# User
spring:
  security:
    user:
      name: zest
      password: 9787
# Datasource
  datasource:
    name: defaultDatasource
    url: jdbc:postgresql://localhost:5432/sample
    username: zest
    password: 9787
    driver-class-name: org.postgresql.Driver

    # hikari
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 3

  # JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # 영속성 설정
    open-in-view: true
    database: postgresql
    show-sql: true

#      <property name="jakarta.persistence.jdbc.driver" value="com.mysql.cj.jdbc.Driver"/>
#      <property name="jakarta.persistence.jdbc.url"
#      value="jdbc:mysql://localhost/jpabegin?characterEncoding=utf8"/>
#      <property name="jakarta.persistence.jdbc.user" value="jpauser"/>
#      <property name="jakarta.persistence.jdbc.password" value="jpapass"/>

# logging
logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: debug
      springframework:
        security: debug